### ISSUE TITLE
Anki has stopped working because of an outdated PyQt version

### ISSUE THREAD

**Issue by afaikiac** [keiqu/inka#183]
Hi! Thank you for the inka!

Unfortunately, I encountered an issue while using qt 6.5.0-3 on Arch Linux.

When I tried using Release 2.2.2, I received a QT error:

```
$ anki
Running with temporary Qt5 compatibility shims.
Run with DISABLE_QT5_COMPAT=1 to confirm compatibility with Qt6.
Traceback (most recent call last):
  File "/home/dl2718/.local/share/pyenv/versions/pyenvx-inka/bin/anki", line 5, in <module>
    from aqt import run
  File "/home/dl2718/.local/share/pyenv/versions/pyenvx-inka/lib/python3.10/site-packages/aqt/__init__.py", line 46, in <module>
    from aqt import gui_hooks
  File "/home/dl2718/.local/share/pyenv/versions/pyenvx-inka/lib/python3.10/site-packages/aqt/gui_hooks.py", line 11, in <module>
    from _aqt.hooks import *
  File "/home/dl2718/.local/share/pyenv/versions/pyenvx-inka/lib/python3.10/site-packages/_aqt/hooks.py", line 18, in <module>
    from aqt.qt import QDialog, QEvent, QMenu, QModelIndex, QWidget, QMimeData
  File "/home/dl2718/.local/share/pyenv/versions/pyenvx-inka/lib/python3.10/site-packages/aqt/qt/__init__.py", line 20, in <module>
    from . import qt5_compat  # needs to be imported first
  File "/home/dl2718/.local/share/pyenv/versions/pyenvx-inka/lib/python3.10/site-packages/aqt/qt/qt5_compat.py", line 18, in <module>
    import PyQt6.QtNetwork
ImportError: /home/dl2718/.local/share/pyenv/versions/pyenvx-inka/lib/python3.10/site-packages/PyQt6/QtNetwork.abi3.so: undefined symbol: _ZN16QNetworkDatagram7destroyEP23QNetworkDatagramPrivate, version Qt_6
```

```
$ DISABLE_QT5_COMPAT=1 anki
Traceback (most recent call last):
  File "/home/dl2718/.local/share/pyenv/versions/pyenvx-inka/bin/anki", line 5, in <module>
    from aqt import run
  File "/home/dl2718/.local/share/pyenv/versions/pyenvx-inka/lib/python3.10/site-packages/aqt/__init__.py", line 46, in <module>
    from aqt import gui_hooks
  File "/home/dl2718/.local/share/pyenv/versions/pyenvx-inka/lib/python3.10/site-packages/aqt/gui_hooks.py", line 11, in <module>
    from _aqt.hooks import *
  File "/home/dl2718/.local/share/pyenv/versions/pyenvx-inka/lib/python3.10/site-packages/_aqt/hooks.py", line 18, in <module>
    from aqt.qt import QDialog, QEvent, QMenu, QModelIndex, QWidget, QMimeData
  File "/home/dl2718/.local/share/pyenv/versions/pyenvx-inka/lib/python3.10/site-packages/aqt/qt/__init__.py", line 21, in <module>
    from .qt6 import *
  File "/home/dl2718/.local/share/pyenv/versions/pyenvx-inka/lib/python3.10/site-packages/aqt/qt/qt6.py", line 16, in <module>
    from PyQt6.QtNetwork import QLocalServer, QLocalSocket, QNetworkProxy
ImportError: /home/dl2718/.local/share/pyenv/versions/pyenvx-inka/lib/python3.10/site-packages/PyQt6/QtNetwork.abi3.so: undefined symbol: _ZN16QNetworkDatagram7destroyEP23QNetworkDatagramPrivate, version Qt_6
```

Do you think it would be helpful to update the release version with the latest versions of PyQt6 and PyQt6-WebEngine (6.5.0)?

**Comment by keiqu** [comment]
Hey! Should be fixed by bump of PyQt6 version. I will do it later today.

**Comment by keiqu** [comment]
Sorry for the delay. Try out new version 2.2.3

**Comment by afaikiac** [comment]
Everything works as expected. Thanks for the update!
